#ifndef MIB_SECOND_SCENARIO
#define  MIB_SECOND_SCENARIO

#if SECOND_1st
	#define FIRST_SCENARIO 0
	#define UPF_SCHED_TICK 1000
	#define UPF_QUEUES_CODEL 0
	#define QFI_QUEUES_CODEL 0
	#define DRB_QUEUES_CODEL 0
	#define DYNAMIC_QUEUE 0
	#define MAX_NUM_PACK_DRB 1024
	#define MAX_NUM_PACK_QFI 1024
#endif

#if SECOND_2nd_10 
	#define FIRST_SCENARIO 0
	#define UPF_SCHED_TICK 1000
	#define UPF_QUEUES_CODEL 0
	#define QFI_QUEUES_CODEL 0
	#define DRB_QUEUES_CODEL 0
	#define DYNAMIC_QUEUE 0
	#define MAX_NUM_PACK_DRB 10
	#define MAX_NUM_PACK_QFI 1024
#endif

#if SECOND_2nd_20 
	#define FIRST_SCENARIO 0
	#define UPF_SCHED_TICK 1000
	#define UPF_QUEUES_CODEL 0
	#define QFI_QUEUES_CODEL 0
	#define DRB_QUEUES_CODEL 0
	#define DYNAMIC_QUEUE 0
	#define MAX_NUM_PACK_DRB 20
	#define MAX_NUM_PACK_QFI 1024
#endif

#if SECOND_2nd_30 
	#define FIRST_SCENARIO 0
	#define UPF_SCHED_TICK 1000
	#define UPF_QUEUES_CODEL 0
	#define QFI_QUEUES_CODEL 0
	#define DRB_QUEUES_CODEL 0
	#define DYNAMIC_QUEUE 0
	#define MAX_NUM_PACK_DRB 30
	#define MAX_NUM_PACK_QFI 1024
#endif


#if SECOND_3rd 
	#define FIRST_SCENARIO 0
	#define UPF_SCHED_TICK 1000
	#define UPF_QUEUES_CODEL 0
	#define QFI_QUEUES_CODEL 0
	#define DRB_QUEUES_CODEL 1
	#define DYNAMIC_QUEUE 0
	#define MAX_NUM_PACK_DRB 1024
	#define MAX_NUM_PACK_QFI 1024
#endif


#if SECOND_4th_10 
	#define FIRST_SCENARIO 0
	#define UPF_SCHED_TICK 1000
	#define UPF_QUEUES_CODEL 0
	#define QFI_QUEUES_CODEL 1
	#define DRB_QUEUES_CODEL 0
	#define DYNAMIC_QUEUE 0
	#define MAX_NUM_PACK_DRB 10
	#define MAX_NUM_PACK_QFI 1024
#endif

#if SECOND_4th_20 
	#define FIRST_SCENARIO 0
	#define UPF_SCHED_TICK 1000
	#define UPF_QUEUES_CODEL 0
	#define QFI_QUEUES_CODEL 1
	#define DRB_QUEUES_CODEL 0
	#define DYNAMIC_QUEUE 0
	#define MAX_NUM_PACK_DRB 20
	#define MAX_NUM_PACK_QFI 1024
#endif

#if SECOND_4th_30 
	#define FIRST_SCENARIO 0
	#define UPF_SCHED_TICK 1000
	#define UPF_QUEUES_CODEL 0
	#define QFI_QUEUES_CODEL 1
	#define DRB_QUEUES_CODEL 0
	#define DYNAMIC_QUEUE 0
	#define MAX_NUM_PACK_DRB 30
	#define MAX_NUM_PACK_QFI 1024
#endif

#if SECOND_5th 
	#define FIRST_SCENARIO 0
	#define UPF_SCHED_TICK 10500
	#define UPF_QUEUES_CODEL 1
	#define QFI_QUEUES_CODEL 0
	#define DRB_QUEUES_CODEL 0
	#define DYNAMIC_QUEUE 0
	#define MAX_NUM_PACK_DRB 1024
	#define MAX_NUM_PACK_QFI 1024
#endif

#if SECOND_6th 
	#define FIRST_SCENARIO 0
	#define UPF_SCHED_TICK 1000
	#define UPF_QUEUES_CODEL 0
	#define QFI_QUEUES_CODEL 1
	#define DRB_QUEUES_CODEL 0
	#define DYNAMIC_QUEUE 1
	#define MAX_NUM_PACK_DRB 1024
	#define MAX_NUM_PACK_QFI 1024
#endif

#if SECOND_7th 
	#define FIRST_SCENARIO 0
	#define UPF_SCHED_TICK 1000
	#define UPF_QUEUES_CODEL 0
	#define QFI_QUEUES_CODEL 0
	#define DRB_QUEUES_CODEL 0
	#define DYNAMIC_QUEUE 0
	#define MAX_NUM_PACK_DRB 1024
	#define MAX_NUM_PACK_QFI 1024
#endif

#if SECOND_8th 
	#define FIRST_SCENARIO 0
	#define UPF_SCHED_TICK 1000
	#define UPF_QUEUES_CODEL 0
	#define QFI_QUEUES_CODEL 0
	#define DRB_QUEUES_CODEL 0
	#define DYNAMIC_QUEUE 0
	#define MAX_NUM_PACK_DRB 10
	#define MAX_NUM_PACK_QFI 2
#endif



#endif

